### PR TITLE
Moved to Scala 2.12.1

### PR DESCRIPTION
**Pull request by dlinov**
Upgraded dependencies to support the newest version of Scala.

### CODE REVIEW

**Comment by fcabestre** [comment]
Well... First, I'm quite surprised and happy there is people still interested in this project. I'll be glad to merge this PR, but still we have to sort out why the build is broken on TravisCI.

**Comment by dlinov** [comment]
Made CI work, please review changes in `.travis.yml`

**Comment by francisdb** [comment]
Can we have a cross build to both 2.11 and 2.12?

**Comment by fcabestre** [comment]
On a regular basis, I try to resume my activity on this pet project. Maybe it's time to try again... With no guaranties ;). I've open an issue for that #9. But first I have to learn how this is usually handled in other projects. If you have any good pointers on that topic for me I'll be grateful @francisdb ;).

**Pull request merged**
